
name: Release to Gradle plugin portal

on:
  workflow_dispatch:
    inputs:
      version:
        description: typescript-generator version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Set version in Maven
        run: mvn versions:set -DnewVersion=${{ inputs.version }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build and publish with Gradle
        run: |
          cd typescript-generator-gradle-plugin
          ./gradlew publishPlugins --validate-only && ./gradlew publishPlugins
        env:
          ORG_GRADLE_PROJECT_version: ${{ inputs.version }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
